//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from YARSpg.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IYARSpgListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class YARSpgBaseListener : IYARSpgListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.yarspg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterYarspg([NotNull] YARSpgParser.YarspgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.yarspg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitYarspg([NotNull] YARSpgParser.YarspgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] YARSpgParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] YARSpgParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] YARSpgParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] YARSpgParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.nodeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNodeDeclaration([NotNull] YARSpgParser.NodeDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.nodeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNodeDeclaration([NotNull] YARSpgParser.NodeDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.relationship"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationship([NotNull] YARSpgParser.RelationshipContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.relationship"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationship([NotNull] YARSpgParser.RelationshipContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.directed"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirected([NotNull] YARSpgParser.DirectedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.directed"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirected([NotNull] YARSpgParser.DirectedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.undirected"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUndirected([NotNull] YARSpgParser.UndirectedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.undirected"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUndirected([NotNull] YARSpgParser.UndirectedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.relationship_label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationship_label([NotNull] YARSpgParser.Relationship_labelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.relationship_label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationship_label([NotNull] YARSpgParser.Relationship_labelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.ido"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdo([NotNull] YARSpgParser.IdoContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.ido"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdo([NotNull] YARSpgParser.IdoContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.node_label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNode_label([NotNull] YARSpgParser.Node_labelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.node_label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNode_label([NotNull] YARSpgParser.Node_labelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.prop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProp([NotNull] YARSpgParser.PropContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.prop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProp([NotNull] YARSpgParser.PropContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKey([NotNull] YARSpgParser.KeyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.key"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKey([NotNull] YARSpgParser.KeyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] YARSpgParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] YARSpgParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.single_key_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingle_key_value([NotNull] YARSpgParser.Single_key_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.single_key_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingle_key_value([NotNull] YARSpgParser.Single_key_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.multiple_key_values"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiple_key_values([NotNull] YARSpgParser.Multiple_key_valuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.multiple_key_values"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiple_key_values([NotNull] YARSpgParser.Multiple_key_valuesContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
