//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from YARSpg.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="YARSpgParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IYARSpgListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.yarspg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterYarspg([NotNull] YARSpgParser.YarspgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.yarspg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitYarspg([NotNull] YARSpgParser.YarspgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] YARSpgParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] YARSpgParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] YARSpgParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] YARSpgParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.nodeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNodeDeclaration([NotNull] YARSpgParser.NodeDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.nodeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNodeDeclaration([NotNull] YARSpgParser.NodeDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.relationship"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationship([NotNull] YARSpgParser.RelationshipContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.relationship"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationship([NotNull] YARSpgParser.RelationshipContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.directed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirected([NotNull] YARSpgParser.DirectedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.directed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirected([NotNull] YARSpgParser.DirectedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.undirected"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUndirected([NotNull] YARSpgParser.UndirectedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.undirected"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUndirected([NotNull] YARSpgParser.UndirectedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.relationship_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationship_label([NotNull] YARSpgParser.Relationship_labelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.relationship_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationship_label([NotNull] YARSpgParser.Relationship_labelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.ido"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdo([NotNull] YARSpgParser.IdoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.ido"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdo([NotNull] YARSpgParser.IdoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.node_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNode_label([NotNull] YARSpgParser.Node_labelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.node_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNode_label([NotNull] YARSpgParser.Node_labelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.prop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProp([NotNull] YARSpgParser.PropContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.prop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProp([NotNull] YARSpgParser.PropContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.key"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKey([NotNull] YARSpgParser.KeyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.key"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKey([NotNull] YARSpgParser.KeyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] YARSpgParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] YARSpgParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.single_key_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingle_key_value([NotNull] YARSpgParser.Single_key_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.single_key_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingle_key_value([NotNull] YARSpgParser.Single_key_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="YARSpgParser.multiple_key_values"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiple_key_values([NotNull] YARSpgParser.Multiple_key_valuesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="YARSpgParser.multiple_key_values"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiple_key_values([NotNull] YARSpgParser.Multiple_key_valuesContext context);
}
