//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from YARSpg.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class YARSpgParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, STRING=11, NUMBER=12, NULL=13, TRUE_FALSE=14, STRING_LITERAL_QUOTE=15, 
		ALNUM_PLUS=16, PN_CHARS=17, PN_CHARS_U=18, UCHAR=19, PN_CHARS_BASE=20, 
		HEX=21, SP=22, NL=23;
	public const int
		RULE_yarspg = 0, RULE_statement = 1, RULE_declaration = 2, RULE_nodeDeclaration = 3, 
		RULE_relationship = 4, RULE_directed = 5, RULE_undirected = 6, RULE_relationship_label = 7, 
		RULE_ido = 8, RULE_node_label = 9, RULE_prop = 10, RULE_key = 11, RULE_value = 12, 
		RULE_single_key_value = 13, RULE_multiple_key_values = 14;
	public static readonly string[] ruleNames = {
		"yarspg", "statement", "declaration", "nodeDeclaration", "relationship", 
		"directed", "undirected", "relationship_label", "ido", "node_label", "prop", 
		"key", "value", "single_key_value", "multiple_key_values"
	};

	private static readonly string[] _LiteralNames = {
		null, "'['", "':'", "']'", "'{'", "','", "'}'", "'('", "')'", "'-'", "'->'", 
		null, null, "'null'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, "STRING", 
		"NUMBER", "NULL", "TRUE_FALSE", "STRING_LITERAL_QUOTE", "ALNUM_PLUS", 
		"PN_CHARS", "PN_CHARS_U", "UCHAR", "PN_CHARS_BASE", "HEX", "SP", "NL"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "YARSpg.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static YARSpgParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public YARSpgParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public YARSpgParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class YarspgContext : ParserRuleContext {
		public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ITerminalNode[] NL() { return GetTokens(YARSpgParser.NL); }
		public ITerminalNode NL(int i) {
			return GetToken(YARSpgParser.NL, i);
		}
		public YarspgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_yarspg; } }
		public override void EnterRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.EnterYarspg(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.ExitYarspg(this);
		}
	}

	[RuleVersion(0)]
	public YarspgContext yarspg() {
		YarspgContext _localctx = new YarspgContext(Context, State);
		EnterRule(_localctx, 0, RULE_yarspg);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 38;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__6 || _la==ALNUM_PLUS) {
				{
				{
				State = 30; statement();
				State = 32;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 31; Match(NL);
					}
					}
					State = 34;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( _la==NL );
				}
				}
				State = 40;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		public DeclarationContext declaration() {
			return GetRuleContext<DeclarationContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 2, RULE_statement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 41; declaration();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DeclarationContext : ParserRuleContext {
		public NodeDeclarationContext nodeDeclaration() {
			return GetRuleContext<NodeDeclarationContext>(0);
		}
		public RelationshipContext relationship() {
			return GetRuleContext<RelationshipContext>(0);
		}
		public DeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_declaration; } }
		public override void EnterRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.EnterDeclaration(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.ExitDeclaration(this);
		}
	}

	[RuleVersion(0)]
	public DeclarationContext declaration() {
		DeclarationContext _localctx = new DeclarationContext(Context, State);
		EnterRule(_localctx, 4, RULE_declaration);
		try {
			State = 45;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ALNUM_PLUS:
				EnterOuterAlt(_localctx, 1);
				{
				State = 43; nodeDeclaration();
				}
				break;
			case T__6:
				EnterOuterAlt(_localctx, 2);
				{
				State = 44; relationship();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NodeDeclarationContext : ParserRuleContext {
		public IdoContext ido() {
			return GetRuleContext<IdoContext>(0);
		}
		public PropContext[] prop() {
			return GetRuleContexts<PropContext>();
		}
		public PropContext prop(int i) {
			return GetRuleContext<PropContext>(i);
		}
		public Node_labelContext[] node_label() {
			return GetRuleContexts<Node_labelContext>();
		}
		public Node_labelContext node_label(int i) {
			return GetRuleContext<Node_labelContext>(i);
		}
		public NodeDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_nodeDeclaration; } }
		public override void EnterRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.EnterNodeDeclaration(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.ExitNodeDeclaration(this);
		}
	}

	[RuleVersion(0)]
	public NodeDeclarationContext nodeDeclaration() {
		NodeDeclarationContext _localctx = new NodeDeclarationContext(Context, State);
		EnterRule(_localctx, 6, RULE_nodeDeclaration);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 47; ido();
			State = 59;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__0) {
				{
				State = 48; Match(T__0);
				State = 49; node_label();
				State = 54;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__1) {
					{
					{
					State = 50; Match(T__1);
					State = 51; node_label();
					}
					}
					State = 56;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 57; Match(T__2);
				}
			}

			State = 61; Match(T__1);
			State = 62; Match(T__3);
			State = 63; prop();
			State = 68;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__4) {
				{
				{
				State = 64; Match(T__4);
				State = 65; prop();
				}
				}
				State = 70;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 71; Match(T__5);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelationshipContext : ParserRuleContext {
		public DirectedContext directed() {
			return GetRuleContext<DirectedContext>(0);
		}
		public UndirectedContext undirected() {
			return GetRuleContext<UndirectedContext>(0);
		}
		public RelationshipContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relationship; } }
		public override void EnterRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.EnterRelationship(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.ExitRelationship(this);
		}
	}

	[RuleVersion(0)]
	public RelationshipContext relationship() {
		RelationshipContext _localctx = new RelationshipContext(Context, State);
		EnterRule(_localctx, 8, RULE_relationship);
		try {
			State = 75;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 73; directed();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 74; undirected();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DirectedContext : ParserRuleContext {
		public IdoContext[] ido() {
			return GetRuleContexts<IdoContext>();
		}
		public IdoContext ido(int i) {
			return GetRuleContext<IdoContext>(i);
		}
		public Relationship_labelContext relationship_label() {
			return GetRuleContext<Relationship_labelContext>(0);
		}
		public PropContext[] prop() {
			return GetRuleContexts<PropContext>();
		}
		public PropContext prop(int i) {
			return GetRuleContext<PropContext>(i);
		}
		public DirectedContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_directed; } }
		public override void EnterRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.EnterDirected(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.ExitDirected(this);
		}
	}

	[RuleVersion(0)]
	public DirectedContext directed() {
		DirectedContext _localctx = new DirectedContext(Context, State);
		EnterRule(_localctx, 10, RULE_directed);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 77; Match(T__6);
			State = 78; ido();
			State = 79; Match(T__7);
			State = 80; Match(T__8);
			State = 81; Match(T__0);
			State = 82; relationship_label();
			State = 96;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__3) {
				{
				{
				State = 83; Match(T__3);
				State = 84; prop();
				State = 89;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__4) {
					{
					{
					State = 85; Match(T__4);
					State = 86; prop();
					}
					}
					State = 91;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 92; Match(T__5);
				}
				}
				State = 98;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 99; Match(T__2);
			State = 100; Match(T__9);
			State = 101; Match(T__6);
			State = 102; ido();
			State = 103; Match(T__7);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UndirectedContext : ParserRuleContext {
		public IdoContext[] ido() {
			return GetRuleContexts<IdoContext>();
		}
		public IdoContext ido(int i) {
			return GetRuleContext<IdoContext>(i);
		}
		public Relationship_labelContext relationship_label() {
			return GetRuleContext<Relationship_labelContext>(0);
		}
		public PropContext[] prop() {
			return GetRuleContexts<PropContext>();
		}
		public PropContext prop(int i) {
			return GetRuleContext<PropContext>(i);
		}
		public UndirectedContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_undirected; } }
		public override void EnterRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.EnterUndirected(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.ExitUndirected(this);
		}
	}

	[RuleVersion(0)]
	public UndirectedContext undirected() {
		UndirectedContext _localctx = new UndirectedContext(Context, State);
		EnterRule(_localctx, 12, RULE_undirected);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 105; Match(T__6);
			State = 106; ido();
			State = 107; Match(T__7);
			State = 108; Match(T__8);
			State = 109; Match(T__0);
			State = 110; relationship_label();
			State = 124;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__3) {
				{
				{
				State = 111; Match(T__3);
				State = 112; prop();
				State = 117;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__4) {
					{
					{
					State = 113; Match(T__4);
					State = 114; prop();
					}
					}
					State = 119;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 120; Match(T__5);
				}
				}
				State = 126;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 127; Match(T__2);
			State = 128; Match(T__8);
			State = 129; Match(T__6);
			State = 130; ido();
			State = 131; Match(T__7);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Relationship_labelContext : ParserRuleContext {
		public ITerminalNode ALNUM_PLUS() { return GetToken(YARSpgParser.ALNUM_PLUS, 0); }
		public Relationship_labelContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relationship_label; } }
		public override void EnterRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.EnterRelationship_label(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.ExitRelationship_label(this);
		}
	}

	[RuleVersion(0)]
	public Relationship_labelContext relationship_label() {
		Relationship_labelContext _localctx = new Relationship_labelContext(Context, State);
		EnterRule(_localctx, 14, RULE_relationship_label);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 133; Match(ALNUM_PLUS);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdoContext : ParserRuleContext {
		public ITerminalNode ALNUM_PLUS() { return GetToken(YARSpgParser.ALNUM_PLUS, 0); }
		public IdoContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ido; } }
		public override void EnterRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.EnterIdo(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.ExitIdo(this);
		}
	}

	[RuleVersion(0)]
	public IdoContext ido() {
		IdoContext _localctx = new IdoContext(Context, State);
		EnterRule(_localctx, 16, RULE_ido);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 135; Match(ALNUM_PLUS);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Node_labelContext : ParserRuleContext {
		public ITerminalNode ALNUM_PLUS() { return GetToken(YARSpgParser.ALNUM_PLUS, 0); }
		public Node_labelContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_node_label; } }
		public override void EnterRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.EnterNode_label(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.ExitNode_label(this);
		}
	}

	[RuleVersion(0)]
	public Node_labelContext node_label() {
		Node_labelContext _localctx = new Node_labelContext(Context, State);
		EnterRule(_localctx, 18, RULE_node_label);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 137; Match(ALNUM_PLUS);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PropContext : ParserRuleContext {
		public KeyContext key() {
			return GetRuleContext<KeyContext>(0);
		}
		public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public PropContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prop; } }
		public override void EnterRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.EnterProp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.ExitProp(this);
		}
	}

	[RuleVersion(0)]
	public PropContext prop() {
		PropContext _localctx = new PropContext(Context, State);
		EnterRule(_localctx, 20, RULE_prop);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 139; key();
			State = 140; Match(T__1);
			State = 141; value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class KeyContext : ParserRuleContext {
		public ITerminalNode ALNUM_PLUS() { return GetToken(YARSpgParser.ALNUM_PLUS, 0); }
		public KeyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_key; } }
		public override void EnterRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.EnterKey(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.ExitKey(this);
		}
	}

	[RuleVersion(0)]
	public KeyContext key() {
		KeyContext _localctx = new KeyContext(Context, State);
		EnterRule(_localctx, 22, RULE_key);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 143; Match(ALNUM_PLUS);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		public Single_key_valueContext single_key_value() {
			return GetRuleContext<Single_key_valueContext>(0);
		}
		public Multiple_key_valuesContext multiple_key_values() {
			return GetRuleContext<Multiple_key_valuesContext>(0);
		}
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		public override void EnterRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.EnterValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.ExitValue(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 24, RULE_value);
		try {
			State = 147;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case STRING:
			case NUMBER:
			case NULL:
			case TRUE_FALSE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 145; single_key_value();
				}
				break;
			case T__0:
				EnterOuterAlt(_localctx, 2);
				{
				State = 146; multiple_key_values();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Single_key_valueContext : ParserRuleContext {
		public ITerminalNode STRING() { return GetToken(YARSpgParser.STRING, 0); }
		public ITerminalNode NUMBER() { return GetToken(YARSpgParser.NUMBER, 0); }
		public ITerminalNode NULL() { return GetToken(YARSpgParser.NULL, 0); }
		public ITerminalNode TRUE_FALSE() { return GetToken(YARSpgParser.TRUE_FALSE, 0); }
		public Single_key_valueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_single_key_value; } }
		public override void EnterRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.EnterSingle_key_value(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.ExitSingle_key_value(this);
		}
	}

	[RuleVersion(0)]
	public Single_key_valueContext single_key_value() {
		Single_key_valueContext _localctx = new Single_key_valueContext(Context, State);
		EnterRule(_localctx, 26, RULE_single_key_value);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 149;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << STRING) | (1L << NUMBER) | (1L << NULL) | (1L << TRUE_FALSE))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Multiple_key_valuesContext : ParserRuleContext {
		public Single_key_valueContext[] single_key_value() {
			return GetRuleContexts<Single_key_valueContext>();
		}
		public Single_key_valueContext single_key_value(int i) {
			return GetRuleContext<Single_key_valueContext>(i);
		}
		public Multiple_key_valuesContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_multiple_key_values; } }
		public override void EnterRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.EnterMultiple_key_values(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IYARSpgListener typedListener = listener as IYARSpgListener;
			if (typedListener != null) typedListener.ExitMultiple_key_values(this);
		}
	}

	[RuleVersion(0)]
	public Multiple_key_valuesContext multiple_key_values() {
		Multiple_key_valuesContext _localctx = new Multiple_key_valuesContext(Context, State);
		EnterRule(_localctx, 28, RULE_multiple_key_values);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 151; Match(T__0);
			State = 152; single_key_value();
			State = 157;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__4) {
				{
				{
				State = 153; Match(T__4);
				State = 154; single_key_value();
				}
				}
				State = 159;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 160; Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x19', '\xA5', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x3', 
		'\x2', '\x3', '\x2', '\x6', '\x2', '#', '\n', '\x2', '\r', '\x2', '\xE', 
		'\x2', '$', '\a', '\x2', '\'', '\n', '\x2', '\f', '\x2', '\xE', '\x2', 
		'*', '\v', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', 
		'\x5', '\x4', '\x30', '\n', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\a', '\x5', '\x37', '\n', '\x5', '\f', 
		'\x5', '\xE', '\x5', ':', '\v', '\x5', '\x3', '\x5', '\x3', '\x5', '\x5', 
		'\x5', '>', '\n', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\a', '\x5', '\x45', '\n', '\x5', '\f', '\x5', '\xE', 
		'\x5', 'H', '\v', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x5', '\x6', 'N', '\n', '\x6', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\a', '\a', 'Z', '\n', '\a', '\f', '\a', '\xE', 
		'\a', ']', '\v', '\a', '\x3', '\a', '\x3', '\a', '\a', '\a', '\x61', '\n', 
		'\a', '\f', '\a', '\xE', '\a', '\x64', '\v', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\a', '\b', 'v', '\n', '\b', 
		'\f', '\b', '\xE', '\b', 'y', '\v', '\b', '\x3', '\b', '\x3', '\b', '\a', 
		'\b', '}', '\n', '\b', '\f', '\b', '\xE', '\b', '\x80', '\v', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', 
		'\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', 
		'\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x5', '\xE', '\x96', '\n', '\xE', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\a', '\x10', '\x9E', '\n', '\x10', '\f', '\x10', '\xE', 
		'\x10', '\xA1', '\v', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x2', '\x2', '\x11', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', 
		'\x12', '\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', '\x2', '\x3', 
		'\x3', '\x2', '\r', '\x10', '\x2', '\xA2', '\x2', '(', '\x3', '\x2', '\x2', 
		'\x2', '\x4', '+', '\x3', '\x2', '\x2', '\x2', '\x6', '/', '\x3', '\x2', 
		'\x2', '\x2', '\b', '\x31', '\x3', '\x2', '\x2', '\x2', '\n', 'M', '\x3', 
		'\x2', '\x2', '\x2', '\f', 'O', '\x3', '\x2', '\x2', '\x2', '\xE', 'k', 
		'\x3', '\x2', '\x2', '\x2', '\x10', '\x87', '\x3', '\x2', '\x2', '\x2', 
		'\x12', '\x89', '\x3', '\x2', '\x2', '\x2', '\x14', '\x8B', '\x3', '\x2', 
		'\x2', '\x2', '\x16', '\x8D', '\x3', '\x2', '\x2', '\x2', '\x18', '\x91', 
		'\x3', '\x2', '\x2', '\x2', '\x1A', '\x95', '\x3', '\x2', '\x2', '\x2', 
		'\x1C', '\x97', '\x3', '\x2', '\x2', '\x2', '\x1E', '\x99', '\x3', '\x2', 
		'\x2', '\x2', ' ', '\"', '\x5', '\x4', '\x3', '\x2', '!', '#', '\a', '\x19', 
		'\x2', '\x2', '\"', '!', '\x3', '\x2', '\x2', '\x2', '#', '$', '\x3', 
		'\x2', '\x2', '\x2', '$', '\"', '\x3', '\x2', '\x2', '\x2', '$', '%', 
		'\x3', '\x2', '\x2', '\x2', '%', '\'', '\x3', '\x2', '\x2', '\x2', '&', 
		' ', '\x3', '\x2', '\x2', '\x2', '\'', '*', '\x3', '\x2', '\x2', '\x2', 
		'(', '&', '\x3', '\x2', '\x2', '\x2', '(', ')', '\x3', '\x2', '\x2', '\x2', 
		')', '\x3', '\x3', '\x2', '\x2', '\x2', '*', '(', '\x3', '\x2', '\x2', 
		'\x2', '+', ',', '\x5', '\x6', '\x4', '\x2', ',', '\x5', '\x3', '\x2', 
		'\x2', '\x2', '-', '\x30', '\x5', '\b', '\x5', '\x2', '.', '\x30', '\x5', 
		'\n', '\x6', '\x2', '/', '-', '\x3', '\x2', '\x2', '\x2', '/', '.', '\x3', 
		'\x2', '\x2', '\x2', '\x30', '\a', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'=', '\x5', '\x12', '\n', '\x2', '\x32', '\x33', '\a', '\x3', '\x2', '\x2', 
		'\x33', '\x38', '\x5', '\x14', '\v', '\x2', '\x34', '\x35', '\a', '\x4', 
		'\x2', '\x2', '\x35', '\x37', '\x5', '\x14', '\v', '\x2', '\x36', '\x34', 
		'\x3', '\x2', '\x2', '\x2', '\x37', ':', '\x3', '\x2', '\x2', '\x2', '\x38', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '\x38', '\x39', '\x3', '\x2', '\x2', 
		'\x2', '\x39', ';', '\x3', '\x2', '\x2', '\x2', ':', '\x38', '\x3', '\x2', 
		'\x2', '\x2', ';', '<', '\a', '\x5', '\x2', '\x2', '<', '>', '\x3', '\x2', 
		'\x2', '\x2', '=', '\x32', '\x3', '\x2', '\x2', '\x2', '=', '>', '\x3', 
		'\x2', '\x2', '\x2', '>', '?', '\x3', '\x2', '\x2', '\x2', '?', '@', '\a', 
		'\x4', '\x2', '\x2', '@', '\x41', '\a', '\x6', '\x2', '\x2', '\x41', '\x46', 
		'\x5', '\x16', '\f', '\x2', '\x42', '\x43', '\a', '\a', '\x2', '\x2', 
		'\x43', '\x45', '\x5', '\x16', '\f', '\x2', '\x44', '\x42', '\x3', '\x2', 
		'\x2', '\x2', '\x45', 'H', '\x3', '\x2', '\x2', '\x2', '\x46', '\x44', 
		'\x3', '\x2', '\x2', '\x2', '\x46', 'G', '\x3', '\x2', '\x2', '\x2', 'G', 
		'I', '\x3', '\x2', '\x2', '\x2', 'H', '\x46', '\x3', '\x2', '\x2', '\x2', 
		'I', 'J', '\a', '\b', '\x2', '\x2', 'J', '\t', '\x3', '\x2', '\x2', '\x2', 
		'K', 'N', '\x5', '\f', '\a', '\x2', 'L', 'N', '\x5', '\xE', '\b', '\x2', 
		'M', 'K', '\x3', '\x2', '\x2', '\x2', 'M', 'L', '\x3', '\x2', '\x2', '\x2', 
		'N', '\v', '\x3', '\x2', '\x2', '\x2', 'O', 'P', '\a', '\t', '\x2', '\x2', 
		'P', 'Q', '\x5', '\x12', '\n', '\x2', 'Q', 'R', '\a', '\n', '\x2', '\x2', 
		'R', 'S', '\a', '\v', '\x2', '\x2', 'S', 'T', '\a', '\x3', '\x2', '\x2', 
		'T', '\x62', '\x5', '\x10', '\t', '\x2', 'U', 'V', '\a', '\x6', '\x2', 
		'\x2', 'V', '[', '\x5', '\x16', '\f', '\x2', 'W', 'X', '\a', '\a', '\x2', 
		'\x2', 'X', 'Z', '\x5', '\x16', '\f', '\x2', 'Y', 'W', '\x3', '\x2', '\x2', 
		'\x2', 'Z', ']', '\x3', '\x2', '\x2', '\x2', '[', 'Y', '\x3', '\x2', '\x2', 
		'\x2', '[', '\\', '\x3', '\x2', '\x2', '\x2', '\\', '^', '\x3', '\x2', 
		'\x2', '\x2', ']', '[', '\x3', '\x2', '\x2', '\x2', '^', '_', '\a', '\b', 
		'\x2', '\x2', '_', '\x61', '\x3', '\x2', '\x2', '\x2', '`', 'U', '\x3', 
		'\x2', '\x2', '\x2', '\x61', '\x64', '\x3', '\x2', '\x2', '\x2', '\x62', 
		'`', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', '\x3', '\x2', '\x2', 
		'\x2', '\x63', '\x65', '\x3', '\x2', '\x2', '\x2', '\x64', '\x62', '\x3', 
		'\x2', '\x2', '\x2', '\x65', '\x66', '\a', '\x5', '\x2', '\x2', '\x66', 
		'g', '\a', '\f', '\x2', '\x2', 'g', 'h', '\a', '\t', '\x2', '\x2', 'h', 
		'i', '\x5', '\x12', '\n', '\x2', 'i', 'j', '\a', '\n', '\x2', '\x2', 'j', 
		'\r', '\x3', '\x2', '\x2', '\x2', 'k', 'l', '\a', '\t', '\x2', '\x2', 
		'l', 'm', '\x5', '\x12', '\n', '\x2', 'm', 'n', '\a', '\n', '\x2', '\x2', 
		'n', 'o', '\a', '\v', '\x2', '\x2', 'o', 'p', '\a', '\x3', '\x2', '\x2', 
		'p', '~', '\x5', '\x10', '\t', '\x2', 'q', 'r', '\a', '\x6', '\x2', '\x2', 
		'r', 'w', '\x5', '\x16', '\f', '\x2', 's', 't', '\a', '\a', '\x2', '\x2', 
		't', 'v', '\x5', '\x16', '\f', '\x2', 'u', 's', '\x3', '\x2', '\x2', '\x2', 
		'v', 'y', '\x3', '\x2', '\x2', '\x2', 'w', 'u', '\x3', '\x2', '\x2', '\x2', 
		'w', 'x', '\x3', '\x2', '\x2', '\x2', 'x', 'z', '\x3', '\x2', '\x2', '\x2', 
		'y', 'w', '\x3', '\x2', '\x2', '\x2', 'z', '{', '\a', '\b', '\x2', '\x2', 
		'{', '}', '\x3', '\x2', '\x2', '\x2', '|', 'q', '\x3', '\x2', '\x2', '\x2', 
		'}', '\x80', '\x3', '\x2', '\x2', '\x2', '~', '|', '\x3', '\x2', '\x2', 
		'\x2', '~', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x81', '\x3', 
		'\x2', '\x2', '\x2', '\x80', '~', '\x3', '\x2', '\x2', '\x2', '\x81', 
		'\x82', '\a', '\x5', '\x2', '\x2', '\x82', '\x83', '\a', '\v', '\x2', 
		'\x2', '\x83', '\x84', '\a', '\t', '\x2', '\x2', '\x84', '\x85', '\x5', 
		'\x12', '\n', '\x2', '\x85', '\x86', '\a', '\n', '\x2', '\x2', '\x86', 
		'\xF', '\x3', '\x2', '\x2', '\x2', '\x87', '\x88', '\a', '\x12', '\x2', 
		'\x2', '\x88', '\x11', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', '\a', 
		'\x12', '\x2', '\x2', '\x8A', '\x13', '\x3', '\x2', '\x2', '\x2', '\x8B', 
		'\x8C', '\a', '\x12', '\x2', '\x2', '\x8C', '\x15', '\x3', '\x2', '\x2', 
		'\x2', '\x8D', '\x8E', '\x5', '\x18', '\r', '\x2', '\x8E', '\x8F', '\a', 
		'\x4', '\x2', '\x2', '\x8F', '\x90', '\x5', '\x1A', '\xE', '\x2', '\x90', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\x91', '\x92', '\a', '\x12', '\x2', 
		'\x2', '\x92', '\x19', '\x3', '\x2', '\x2', '\x2', '\x93', '\x96', '\x5', 
		'\x1C', '\xF', '\x2', '\x94', '\x96', '\x5', '\x1E', '\x10', '\x2', '\x95', 
		'\x93', '\x3', '\x2', '\x2', '\x2', '\x95', '\x94', '\x3', '\x2', '\x2', 
		'\x2', '\x96', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x97', '\x98', '\t', 
		'\x2', '\x2', '\x2', '\x98', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x99', 
		'\x9A', '\a', '\x3', '\x2', '\x2', '\x9A', '\x9F', '\x5', '\x1C', '\xF', 
		'\x2', '\x9B', '\x9C', '\a', '\a', '\x2', '\x2', '\x9C', '\x9E', '\x5', 
		'\x1C', '\xF', '\x2', '\x9D', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x9E', 
		'\xA1', '\x3', '\x2', '\x2', '\x2', '\x9F', '\x9D', '\x3', '\x2', '\x2', 
		'\x2', '\x9F', '\xA0', '\x3', '\x2', '\x2', '\x2', '\xA0', '\xA2', '\x3', 
		'\x2', '\x2', '\x2', '\xA1', '\x9F', '\x3', '\x2', '\x2', '\x2', '\xA2', 
		'\xA3', '\a', '\x5', '\x2', '\x2', '\xA3', '\x1F', '\x3', '\x2', '\x2', 
		'\x2', '\xF', '$', '(', '/', '\x38', '=', '\x46', 'M', '[', '\x62', 'w', 
		'~', '\x95', '\x9F',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
